pipeline {
   agent any

   stages {
      stage("Limpando o workspace") {
         steps {
            sh "pwd"
            deleteDir()
         }
      }

      stage("Clonando o projeto do GitHub") {
         steps {
            git credentialsId: "do-25", url: "git@github.com:rmleme/do-25.git"
         }
      }

      stage("Rodandos os testes unitários") {
         steps {
            sh "mvn clean test"
         }
      }

      stage("Gerando o artefato") {
         steps {
            sh "mvn package -DskipTests"
         }
      }

      stage("Solicitando aprovação") {
         steps {
            script {
                slackSend(color: "warning", message: "Para aprovar este deploy, clique aqui: ${JOB_URL} - [Janela de 5 minutos]", channel: "CVB6B7SJ2")
                timeout(time: 5, unit: "MINUTES") {
                    input(id: "Deploy Decision", message: "Desejar aprovar o deploy?", ok: "Deploy")
                }
            }
         }
      }

      stage(deploy) {
         steps {
            sh "scp -o StrictHostKeyChecking=no -i /home/vagrant/devops target/alura-forum.war vagrant@192.168.33.11:/home/vagrant/alura-forum.war"
            sh "ssh -o StrictHostKeyChecking=no -i /home/vagrant/devops vagrant@192.168.33.11 'sudo mv /home/vagrant/alura-forum.war /var/lib/tomcat8/webapps/alura-forum.war'"
         }
      }
   }
}