pipeline {
   agent any

   stages {
      stage("Notificando início") {
         steps {
            script {
                slackSend(color: "info", message: "Iniciando build ${BUILD_NUMBER} do job ${JOB_NAME}. Para acompanhar o build, clique em ${JOB_URL}", channel: "CVB6B7SJ2")
            }
         }
      }

      stage("Limpando o workspace") {
         steps {
            sh "pwd"
            deleteDir()
         }
      }

      stage("Clonando o projeto do GitHub") {
         steps {
            git credentialsId: "do-25", url: "git@github.com:rmleme/do-25.git"
         }
      }

      stage("Rodandos os testes unitários") {
         steps {
            sh "mvn clean test"
         }
      }

      stage("Gerando o artefato") {
         steps {
            sh "mvn package -DskipTests"
         }
      }

      stage(Deploy) {
         steps {
            sh "ssh -o StrictHostKeyChecking=no -i /home/vagrant/devops vagrant@192.168.33.11 'sudo rm -f /var/lib/tomcat8/webapps/alura-forum.war'"
            sh "scp -o StrictHostKeyChecking=no -i /home/vagrant/devops target/alura-forum.war vagrant@192.168.33.11:/home/vagrant/alura-forum.war"
            sh "ssh -o StrictHostKeyChecking=no -i /home/vagrant/devops vagrant@192.168.33.11 'sudo mv /home/vagrant/alura-forum.war /var/lib/tomcat8/webapps/alura-forum.war'"
         }
      }

      stage("Notificando término") {
         steps {
            script {
                slackSend(color: "info", message: "Build ${BUILD_NUMBER} do job ${JOB_NAME} concluído com sucesso. Resultado disponível em ${JOB_URL}", channel: "CVB6B7SJ2")
            }
         }
      }
   }
}