Vagrant.configure("2") do |config|
  config.vm.define "db" do |db|
    db.vm.box = "debian/stretch64"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.10"
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/db.yml"
    end
  end

  config.vm.define "web" do |web|
    web.vm.box = "debian/stretch64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.11"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/web.yml"
    end
  end

  config.vm.define "web02" do |web02|
    web02.vm.box = "debian/stretch64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.33.12"
    web02.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/web.yml"
    end
  end

  config.vm.define "lb" do |lb|
    lb.vm.box = "debian/stretch64"
    lb.vm.hostname = "nginx"
    lb.vm.network "private_network", ip: "192.168.33.20"
    lb.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/lb.yml"
    end
  end

  config.vm.define "ci" do |ci|
    ci.vm.box = "debian/stretch64"
    ci.vm.network "private_network", ip: "192.168.50.12"
    ci.vm.hostname = "jenkins"
	ci.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/ci.yml"
	end
  end
end