- hosts: all
  tasks:
    - name: Add Jenkins repository's key
      become: 'yes'
      apt_key:
        url: 'http://pkg.jenkins.io/debian/jenkins.io.key'
    - name: Add Jenkins repository
      become: 'yes'
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    - name: Update apt
      become: 'yes'
      apt:
        update_cache: 'yes'
        cache_valid_time: 3600
    - name: Install Java & Maven
      become: 'yes'
      apt:
        name:
          - openjdk-8-jdk-headless
          - maven
    - name: Install Jenkins
      become: 'yes'
      apt:
        name: jenkins
    - name: Install git
      become: 'yes'
      apt:
        name: git
    - name: Copy web SSH private key
      become: 'yes'
      copy:
        src: ../ssh-keys/devops
        dest: /home/vagrant/devops
        mode: 0400
        owner: jenkins
        group: jenkins