- hosts: all
  tasks:
    - name: Update apt
      become: 'yes'
      apt:
        update_cache: 'yes'
    - name: Install Java and Tomcat
      become: 'yes'
      apt:
        name:
          - openjdk-8-jre
          - tomcat8
        state: present
    - name: Copy web application to VM
      become: 'yes'
      copy:
        src: ../../target/alura-forum.war
        dest: /var/lib/tomcat8/webapps/alura-forum.war